substitutions:
  _IMAGE: tts-backend

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - tts-backend/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
